name: test
on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        domains: 
          - "aorfanos.com"
          - "saikolab.com"

    steps:
      - uses: actions/checkout@v1
      
      - run: |
          ./propagationChecker.sh -c A aorfanos.com
